NCP2286: Upgrade to pc-ble-driver 4.1.0 (#217)
* Use find_package for pc-ble-driver 4.1.0

Use find_package instead of submodule for pc-ble-driver, and remove
said submodule. This also upgrades pc-ble-driver to 4.1.0.

EnumSerialPorts from nrf-ble-driver has changed signature. It now
returns a list instead of filling a provided one.

* Use 1m baud rate on Macos

Macos has gained support for this. It is no longer necessary to limit it
to 115k.

* Install connectivity firmware on build

CMake install target will now install/update the connectivity firmware
hex files from the nrf-ble-driver package in case it's old or missing.
build.js now invokes the install target.

* Disuse private pc-ble-driver API EnumSerialPorts

EnumSerialPorts is a private API. This change replaces its use with the
public API sd_rpc_serial_port_enum.

* Add support for VCPKG_ROOT envvar

* Update firmwareRegistry to connectivity 4.1.0

* Define package contents

Without this or a .npmignore, npm pack looks at .gitingore. .gitignore
would prevent pc-ble-driver/ from inclusion. This also reduces size and
file count of package.

* Work around race in grabAdapter

Resolving grabAdapter promises concurrently results in a race, which
most of the time results in the error:

Error: Error occured when open device long term. Errorcode: CouldNotCallFunction (0x9)
    Lowlevel error: INVALID_OPERATION (fffffffe)

* Extend test timeout; needed for nRF52 dongles

When two nRF52 dongles need programming, the device setup can take about
40 seconds on my machine.

* Require cmake-js variables during configure

* Update install instructions in README

* Correct eslintrc structure

* Remove requirements on node and npm versions

These were outdated document and don't reflect reality.