Fix issue with tests not running
jest tests fails because newer jsdom
versions throws error:

SecurityError: localStorage is not available for opaque origins

Updating to newer version of jest is supposed to fix this:
https://github.com/jsdom/jsdom/issues/2304